[build] Update to latest revisions of upstream layers
ros/meta-ros pull request #807
Opened 2021-02-26 19:04 UTC by shr-project

2021-03-22 07:25 UTC, shr-project commented
Will be updated to include new meta-ros revisions to include https://github.com/ros/meta-ros/pull/809

2021-03-22 18:41 UTC, herb-kuta-lge requested changes
files/*.mcf need the copyright year updated.

2021-03-22 23:27 UTC, herb-kuta-lge approved these changes

2021-04-04 18:27 UTC, merged

2021-04-04 18:27 UTC, shr-project commented
Also in build-next:
   6ea252c1f..e88327c42  build -> build-next